kcms.api.url=http://las.daegu.go.kr:8081/kdotapi/ksearchapi/

sangho.api.url=http://59.20.71.44:9091/LILLWebApi/LILLAPI.jsp

#data4library.api.key=06cf4439cb5528d8ef364ac1cef48a2182aab61dfa1082fe74c0336e6fb194bf
data4library.api.key=f74f5a85d8ec79a2a8db9728d19240d5ddd2dd6e93711f318a3b7ae505853fd0
data4library.api.url=http://data4library.kr/api/


ilus.api.url=
libone.api.url=