kcms.api.url=http://las.daegu.go.kr:8081/kdotapi/ksearchapi/

kcms.private.api.url=http://las.daegu.go.kr:8081/kdotapi_p/ksearchapi/

sangho.api.url=http://59.20.71.44:9091/LILLWebApi/LILLAPI.jsp

keyword.api.url=http://152.99.21.156:9901/

libraryapi.api.url=https://las.daegu.go.kr/baro/libraryapi/

#data4library.api.key=06cf4439cb5528d8ef364ac1cef48a2182aab61dfa1082fe74c0336e6fb194bf
data4library.api.key=f74f5a85d8ec79a2a8db9728d19240d5ddd2dd6e93711f318a3b7ae505853fd0
data4library.api.url=http://data4library.kr/api/

culture.api.url=http://www.culture.go.kr/openapi/rest/
culture.api.key=sJ1NoVQBK2nsNP4b1R0%2BsSWiFRByMlaG2VdTRnnLsUtnlpsworjKd4fvoET7YMk1xjMt%2BCIwqJu7%2BRyahrIhnQ%3D%3D


ilus.api.url=
libone.api.url=

point.api.url = http://pointlib.daegu.go.kr/infosetapi

kakao.api.key='KakaoAK 7469655c1f5e6608afccf48b46aabf0c'

#kcms.api.url=http://las.daegu.go.kr:8081/kdotapi/ksearchapi/

#sangho.api.url=http://152.99.21.154:9999/LILLWebApi/LILLAPI.jsp

#keyword.api.url=http://152.99.21.156:9901/

#data4library.api.key=4f888225b040013a671b86e43a54a2a2149a914a9531ea9c60c3c02d6e7ae012
#data4library.api.url=http://data4library.kr/api/




#ilus.api.url=
#libone.api.url=
