#  key/manage_idx/count
#  Model Key = "board"+index
h1=noticeList/88/4
h2=recommendBookList/94/10,noticeList/97/5,faqList/98/8
h3=noticeList/109/5,movieList/104/18,bookCuration1/345/2,boardList1/384/2
h4=recommendBookList/113/10,movieList/223/18,noticeList/84/5
h5=noticeList/123/5,movieList/121/20,bookCuration1/294/2,bookCuration2/296/2
h6=recommendBookList/233/10,movieList/25/13,noticeList/132/5
h7=recommendBookList/144/10,noticeList/1/5
h8=noticeList/161/4,curationList/290/2,boardList1/341/7
h9=noticeList/56/4,recommendBookList/31/10
h10=noticeList/179/5,bidList/180/7,recommendBookList/174/10
h30=noticeList/284/2