#  key/manage_idx/count
#  Model Key = "board"+index
h1=noticeList/88/6,bidList/394/6
h2=recommendBookList/94/10,noticeList/97/5,faqList/98/8
h3=noticeList/109/5,movieList/104/18,bookCuration1/345/2,boardList1/384/2
h4=recommendBookList/113/10,movieList/223/18,noticeList/84/5
h5=noticeList/123/5,movieList/121/20,bookCuration1/294/2,bookCuration2/296/2,boardList1/474/5
h6=recommendBookList/233/10,movieList/25/13,noticeList/132/5
h7=recommendBookList/144/10,noticeList/1/5,movieList/157/10,exhibitionList/145/10
h8=noticeList/161/4,curationList/290/2,boardList1/341/7
h9=noticeList/56/4,recommendBookList/31/10
h10=noticeList/179/5,bidList/180/7,recommendBookList/174/10
h30=noticeList/284/2
#h34 dmsl
h34=noticeList/752/6,bookList1/744/5,bookList2/745/5,bookList3/746/5
#h35 namdm
h35=noticeList/641/5,bookList1/602/5,movieList/640/5
#h36 namic
h36=noticeList/634/5,bookList1/606/5,movieList/608/5
#h37 dalseolib
h37=bookList1/736/4,movieList/737/1
#h44 dalseonglib
h44=noticeList/689/5,bookList1/683/8,movieList/685/5
#h45 donggu
h45=noticeList/614/4,bookList1/611/3,bookList2/612/3
#h46 bukgu-gususan
h46=noticeList/699/5,bookList1/697/4
#h47 bukgu-dh
h47=noticeList/709/5,bookList1/707/4
#h48 bukgu-tj
h48=noticeList/718/5,bookList1/716/4
#h50 beomeo
h50=noticeList/662/5,bookList1/659/4
#h51 yonghak
h51=noticeList/677/5,bookList1/669/6,boardList1/682/5
#h52 gosan
h52=noticeList/730/5,bookList1/726/6
#h53 junggu
h53=noticeList/652/5

#h79 with
h79=noticeList/1105/5,bookList1/1102/5
#h80 dotory
h80=noticeList/1054/5,bookList1/1058/5
#h81 dongil
h81=noticeList/1064/5,bookList1/1061/5
#h82 vision
h82=noticeList/1068/5,bookList1/1065/5
#h83 saebut
h83=noticeList/1071/5
#h84 art
h84=noticeList/1076/5,bookList1/1074/5
#h85 yeonam
h85=noticeList/1081/5,bookList1/1079/5
#h86 daegubl
h86=noticeList/1087/5,bookList1/1084/5
#h87 wasabi
h87=noticeList/1093/5,bookList1/1090/5
#h88 handle
h88=noticeList/1098/5,bookList1/1096/5
