#  key/manage_idx/count
#  Model Key = "board"+index
h1=noticeList/88/4
h2=newBookBoardList/94/1,noticeList/97/5,faqList/98/8
h3=noticeList/109/5,movieList/104/14
h4=
h5=
h6=
h7=
h8=
h9=
h10=
h30=