localServer.driverClassName=com.tmax.tibero.jdbc.TbDriver
localServer.url=jdbc:tibero:thin:@www.whalesoft.co.kr:3069:tibero
localServer.username=dglib
localServer.password=dglib

localServer2.driverClassName=com.mysql.jdbc.Driver
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_sslib?autoReconnect=true
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_228lib?autoReconnect=true
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_228support?autoReconnect=true
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_bukbu?autoReconnect=true
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_seobu?autoReconnect=true
#localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_jungang?autoReconnect=true
localServer2.url=jdbc:mysql://192.168.0.83:3306/dglib_hublib?autoReconnect=true
localServer2.username=dglib
localServer2.password=dglib1@

localServer3.driverClassName=com.mysql.jdbc.Driver
#localServer3.url=jdbc:mysql://192.168.0.83:3306/dglib_dalsung?autoReconnect=true
#localServer3.url=jdbc:mysql://192.168.0.83:3306/dglib_duryu?autoReconnect=true
localServer3.url=jdbc:mysql://192.168.0.83:3306/dglib_nambu?autoReconnect=true
#localServer3.url=jdbc:mysql://192.168.0.83:3306/dglib_dongbu?autoReconnect=true
#localServer3.url=jdbc:mysql://192.168.0.83:3306/dglib_228minju?autoReconnect=true
localServer3.username=dglib
localServer3.password=dglib1@


devServer.driverClassName=oracle.jdbc.driver.OracleDriver
devServer.url=jdbc:oracle:thin:@www.whalesoft.co.kr:1521:ora12
devServer.username=dev1
devServer.password=whalesoft_dev1