
localServer.driverClassName=com.tmax.tibero.jdbc.TbDriver
localServer.url=jdbc:tibero:thin:@192.168.0.11:8629:tibero
localServer.username=dglib
localServer.password=dglib

localServer2.driverClassName=com.tmax.tibero.jdbc.TbDriver
localServer2.url=jdbc:tibero:thin:@www.whalesoft.co.kr:7629:tibero
localServer2.username=dglib
localServer2.password=dglib

localServer3.driverClassName=com.tmax.tibero.jdbc.TbDriver
localServer3.url=jdbc:tibero:thin:@www.whalesoft.co.kr:7629:tibero
localServer3.username=dglib
localServer3.password=dglib


devServer.driverClassName=com.tmax.tibero.jdbc.TbDriver
devServer.url=jdbc:tibero:thin:@www.whalesoft.co.kr:7629:tibero
devServer.username=dglib
devServer.password=dglib